-- ===========================================================================
-- CP04 - Sistema de Gerenciamento de Biblioteca
-- Script DDL para Oracle. Relacionamento muitos-para-muitos (N:N) entre
-- Autores e Livros materializado pela tabela de juncao TB_LIVROS_AUTORES.
-- ===========================================================================

-- Limpeza (execute apenas se as tabelas ja existirem)
-- DROP TABLE TB_LIVROS_AUTORES CASCADE CONSTRAINTS;
-- DROP TABLE TB_LIVROS CASCADE CONSTRAINTS;
-- DROP TABLE TB_AUTORES CASCADE CONSTRAINTS;

CREATE TABLE TB_AUTORES (
    ID_AUTOR          NUMBER(10)      GENERATED ALWAYS AS IDENTITY,
    NM_AUTOR          VARCHAR2(150)   NOT NULL,
    DS_NACIONALIDADE  VARCHAR2(80)    NOT NULL,
    DT_NASCIMENTO     TIMESTAMP       NOT NULL,
    DT_CRIACAO        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AUTORES PRIMARY KEY (ID_AUTOR)
);

CREATE INDEX IX_AUTORES_NOME ON TB_AUTORES (NM_AUTOR);

CREATE TABLE TB_LIVROS (
    ID_LIVRO            NUMBER(10)      GENERATED ALWAYS AS IDENTITY,
    NM_TITULO           VARCHAR2(200)   NOT NULL,
    CD_ISBN             VARCHAR2(20)    NOT NULL,
    VL_PRECO            NUMBER(10,2)    NOT NULL,
    QT_ESTOQUE          NUMBER(10)      NOT NULL,
    NR_ANO_PUBLICACAO   NUMBER(4)       NOT NULL,
    DT_CRIACAO          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_LIVROS PRIMARY KEY (ID_LIVRO),
    CONSTRAINT UK_LIVROS_ISBN UNIQUE (CD_ISBN),
    CONSTRAINT CK_LIVROS_PRECO CHECK (VL_PRECO > 0),
    CONSTRAINT CK_LIVROS_ESTOQUE CHECK (QT_ESTOQUE >= 0)
);

-- Tabela de juncao do relacionamento N:N.
CREATE TABLE TB_LIVROS_AUTORES (
    ID_LIVRO  NUMBER(10) NOT NULL,
    ID_AUTOR  NUMBER(10) NOT NULL,
    CONSTRAINT PK_LIVROS_AUTORES PRIMARY KEY (ID_LIVRO, ID_AUTOR),
    CONSTRAINT FK_LIVROS_AUTORES_LIVRO FOREIGN KEY (ID_LIVRO)
        REFERENCES TB_LIVROS (ID_LIVRO) ON DELETE CASCADE,
    CONSTRAINT FK_LIVROS_AUTORES_AUTOR FOREIGN KEY (ID_AUTOR)
        REFERENCES TB_AUTORES (ID_AUTOR) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Carga inicial de exemplo
-- ---------------------------------------------------------------------------
INSERT INTO TB_AUTORES (NM_AUTOR, DS_NACIONALIDADE, DT_NASCIMENTO)
VALUES ('Machado de Assis', 'Brasileira', TO_TIMESTAMP('1839-06-21', 'YYYY-MM-DD'));

INSERT INTO TB_AUTORES (NM_AUTOR, DS_NACIONALIDADE, DT_NASCIMENTO)
VALUES ('Clarice Lispector', 'Brasileira', TO_TIMESTAMP('1920-12-10', 'YYYY-MM-DD'));

INSERT INTO TB_LIVROS (NM_TITULO, CD_ISBN, VL_PRECO, QT_ESTOQUE, NR_ANO_PUBLICACAO)
VALUES ('Dom Casmurro', '9788535910663', 39.90, 12, 1899);

INSERT INTO TB_LIVROS (NM_TITULO, CD_ISBN, VL_PRECO, QT_ESTOQUE, NR_ANO_PUBLICACAO)
VALUES ('A Hora da Estrela', '9788520937136', 44.50, 8, 1977);

INSERT INTO TB_LIVROS (NM_TITULO, CD_ISBN, VL_PRECO, QT_ESTOQUE, NR_ANO_PUBLICACAO)
VALUES ('Antologia da Literatura Brasileira', '9788500000001', 89.90, 5, 2020);

-- Livro com dois autores: comprova o relacionamento N:N.
INSERT INTO TB_LIVROS_AUTORES (ID_LIVRO, ID_AUTOR) VALUES (1, 1);
INSERT INTO TB_LIVROS_AUTORES (ID_LIVRO, ID_AUTOR) VALUES (2, 2);
INSERT INTO TB_LIVROS_AUTORES (ID_LIVRO, ID_AUTOR) VALUES (3, 1);
INSERT INTO TB_LIVROS_AUTORES (ID_LIVRO, ID_AUTOR) VALUES (3, 2);

COMMIT;
